### ISSUE TITLE
关于日志输出等级配置

### ISSUE THREAD

**Issue by lesser0** [MrXiaoM/Overflow#64]
当`config/Console/Logger.yml`配置如下时：
```
# 默认日志输出等级
# 可选值: ALL, VERBOSE, DEBUG, INFO, WARNING, ERROR, NONE
defaultPriority: INFO
# 特定日志记录器输出等级
loggers: 
  example.logger: NONE
  console.debug: NONE
  Bot: WARNING
  org.eclipse.aether.internal: INFO
  org.apache.http.wire: INFO
# 是否启动外部日志框架桥接
binding: 
  slf4j: true
```

`logs/onebot/`下的日志仍会记录V/Onebot，而其中D/Onebot包括了全部收发消息
`bots/【qq号】/logs`下的日志仍会记录V/Bot，包括了全部收发消息

不知这两处日志的输出等级是否能配置？
