### ISSUE TITLE
docker的支持

### ISSUE THREAD

**Issue by lumia1998** [MrXiaoM/Overflow#73]
有考虑支持docker吗?目前只看到win的客户端

**Comment by MrXiaoM** [comment]
我并不主要使用 linux，无法提供相应支持

**Comment by Nekoer** [comment]
也许你可以试试我写的这个
```
version: '3'
services:
  overflow:
    image: hcyacg/overflow:latest
    container_name: overflow
    restart: always
    ports:
      - "3001:3001"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /本地的目录/plugins:/overflow/plugins
      - /本地的目录/config:/overflow/config
      - /本地的目录/bots:/overflow/bots
      - /本地的目录/logs:/overflow/logs
      - /本地的目录/data:/overflow/data
    network_mode: bridge
```
我这个是用在nas上的，理论上都可以用
